// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.5
// source: proto/greet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreetSeviceClient is the client API for GreetSevice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetSeviceClient interface {
	SayHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error)
	SayHelloServerStreaming(ctx context.Context, in *NamesList, opts ...grpc.CallOption) (GreetSevice_SayHelloServerStreamingClient, error)
	SayHelloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetSevice_SayHelloClientStreamingClient, error)
	SayHelloBidrectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetSevice_SayHelloBidrectionalStreamingClient, error)
}

type greetSeviceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetSeviceClient(cc grpc.ClientConnInterface) GreetSeviceClient {
	return &greetSeviceClient{cc}
}

func (c *greetSeviceClient) SayHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/greet_service.GreetSevice/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetSeviceClient) SayHelloServerStreaming(ctx context.Context, in *NamesList, opts ...grpc.CallOption) (GreetSevice_SayHelloServerStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetSevice_ServiceDesc.Streams[0], "/greet_service.GreetSevice/SayHelloServerStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetSeviceSayHelloServerStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetSevice_SayHelloServerStreamingClient interface {
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetSeviceSayHelloServerStreamingClient struct {
	grpc.ClientStream
}

func (x *greetSeviceSayHelloServerStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetSeviceClient) SayHelloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetSevice_SayHelloClientStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetSevice_ServiceDesc.Streams[1], "/greet_service.GreetSevice/SayHelloClientStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetSeviceSayHelloClientStreamingClient{stream}
	return x, nil
}

type GreetSevice_SayHelloClientStreamingClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*MessagesList, error)
	grpc.ClientStream
}

type greetSeviceSayHelloClientStreamingClient struct {
	grpc.ClientStream
}

func (x *greetSeviceSayHelloClientStreamingClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetSeviceSayHelloClientStreamingClient) CloseAndRecv() (*MessagesList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MessagesList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetSeviceClient) SayHelloBidrectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetSevice_SayHelloBidrectionalStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetSevice_ServiceDesc.Streams[2], "/greet_service.GreetSevice/SayHelloBidrectionalStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetSeviceSayHelloBidrectionalStreamingClient{stream}
	return x, nil
}

type GreetSevice_SayHelloBidrectionalStreamingClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetSeviceSayHelloBidrectionalStreamingClient struct {
	grpc.ClientStream
}

func (x *greetSeviceSayHelloBidrectionalStreamingClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetSeviceSayHelloBidrectionalStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetSeviceServer is the server API for GreetSevice service.
// All implementations must embed UnimplementedGreetSeviceServer
// for forward compatibility
type GreetSeviceServer interface {
	SayHello(context.Context, *NoParam) (*HelloResponse, error)
	SayHelloServerStreaming(*NamesList, GreetSevice_SayHelloServerStreamingServer) error
	SayHelloClientStreaming(GreetSevice_SayHelloClientStreamingServer) error
	SayHelloBidrectionalStreaming(GreetSevice_SayHelloBidrectionalStreamingServer) error
	mustEmbedUnimplementedGreetSeviceServer()
}

// UnimplementedGreetSeviceServer must be embedded to have forward compatible implementations.
type UnimplementedGreetSeviceServer struct {
}

func (UnimplementedGreetSeviceServer) SayHello(context.Context, *NoParam) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreetSeviceServer) SayHelloServerStreaming(*NamesList, GreetSevice_SayHelloServerStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloServerStreaming not implemented")
}
func (UnimplementedGreetSeviceServer) SayHelloClientStreaming(GreetSevice_SayHelloClientStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloClientStreaming not implemented")
}
func (UnimplementedGreetSeviceServer) SayHelloBidrectionalStreaming(GreetSevice_SayHelloBidrectionalStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloBidrectionalStreaming not implemented")
}
func (UnimplementedGreetSeviceServer) mustEmbedUnimplementedGreetSeviceServer() {}

// UnsafeGreetSeviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetSeviceServer will
// result in compilation errors.
type UnsafeGreetSeviceServer interface {
	mustEmbedUnimplementedGreetSeviceServer()
}

func RegisterGreetSeviceServer(s grpc.ServiceRegistrar, srv GreetSeviceServer) {
	s.RegisterService(&GreetSevice_ServiceDesc, srv)
}

func _GreetSevice_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetSeviceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet_service.GreetSevice/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetSeviceServer).SayHello(ctx, req.(*NoParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetSevice_SayHelloServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NamesList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetSeviceServer).SayHelloServerStreaming(m, &greetSeviceSayHelloServerStreamingServer{stream})
}

type GreetSevice_SayHelloServerStreamingServer interface {
	Send(*HelloResponse) error
	grpc.ServerStream
}

type greetSeviceSayHelloServerStreamingServer struct {
	grpc.ServerStream
}

func (x *greetSeviceSayHelloServerStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetSevice_SayHelloClientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetSeviceServer).SayHelloClientStreaming(&greetSeviceSayHelloClientStreamingServer{stream})
}

type GreetSevice_SayHelloClientStreamingServer interface {
	SendAndClose(*MessagesList) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greetSeviceSayHelloClientStreamingServer struct {
	grpc.ServerStream
}

func (x *greetSeviceSayHelloClientStreamingServer) SendAndClose(m *MessagesList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetSeviceSayHelloClientStreamingServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetSevice_SayHelloBidrectionalStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetSeviceServer).SayHelloBidrectionalStreaming(&greetSeviceSayHelloBidrectionalStreamingServer{stream})
}

type GreetSevice_SayHelloBidrectionalStreamingServer interface {
	Send(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greetSeviceSayHelloBidrectionalStreamingServer struct {
	grpc.ServerStream
}

func (x *greetSeviceSayHelloBidrectionalStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetSeviceSayHelloBidrectionalStreamingServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetSevice_ServiceDesc is the grpc.ServiceDesc for GreetSevice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetSevice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet_service.GreetSevice",
	HandlerType: (*GreetSeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreetSevice_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHelloServerStreaming",
			Handler:       _GreetSevice_SayHelloServerStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHelloClientStreaming",
			Handler:       _GreetSevice_SayHelloClientStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHelloBidrectionalStreaming",
			Handler:       _GreetSevice_SayHelloBidrectionalStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/greet.proto",
}
